### ISSUE TITLE
get error The link was terminated by the modem hanging u

### ISSUE THREAD

**Issue by MatanTubul** [COUR4G3/python-pppd#4]
Hi,
i am trying to use it in mu ubuntu os, but after few seconds i get the following error
this is my inputs:
````
>>> from pppd import PPPConnection
>>> ppp = PPPConnection('/dev/ttyUSB2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pppd.py", line 87, in __init__
    raise PPPConnectionError(self.proc.returncode, self.output)
pppd.PPPConnectionError: The link was terminated by the modem hanging up
>>> 
```
`

**Comment by MatanTubul** [comment]
fixed, i forgot to add the connection script
