### ISSUE TITLE
Failing with python 3.7

### ISSUE THREAD

**Issue by muanis** [COUR4G3/python-pppd#9]
When trying to connect, getting:

```
Traceback (most recent call last):
  File "check_internet.py", line 54, in <module>
    ppp = PPPConnection(call='provider') # blocks until connected
  File "/home/pi/raspberry-pi-projects/sixfab/pppd.py", line 83, in __init__
    self.output += self.proc.stdout.read()
  File "/usr/lib/python3.7/codecs.py", line 321, in decode
    data = self.buffer + input
TypeError: can't concat NoneType to bytes
```

**Comment by COUR4G3** [comment]
It looks like  `proc.stdout` is now None on `.read()` when it has nothing to return in non-blocking mode. It shouldn't be though, need to setup `pppd` on my environment and test this. Ideally I should be using `.communicate()` instead as this is the proper way to do it.

If you need a quick fix, would suggest assigning `self.proc.stdout.read()` into a variable, and checking if it is `None` and then `continue` on the loop. You'll also probably need to do it in the `.laddr`, `.raddr` and `.connected` methods as well.

**Comment by muanis** [comment]
Tried to debug a bit more.

Doing this:

```
 81         while True:
 82             try:
 83                 import pdb; pdb.set_trace()
 84                 outp = self.proc.stdout.read()
 85                 if(outp != None):
 86                     self.output += outp
 87             except IOError as e:
```

Results in this weird behavior where read returns NoneType and the actual error

```
(Pdb) self.proc.stdout
<_io.TextIOWrapper name=4 encoding='UTF-8'>
(Pdb) self.proc.stdout.read()
*** TypeError: can't concat NoneType to bytes
(Pdb) self.proc.stdout
<_io.TextIOWrapper name=4 encoding='UTF-8'>
(Pdb) self.proc.stdout.read()
'Device ttyUSB3 is locked by pid 3962\n'
(Pdb) self.proc.stdout.read()
*** TypeError: can't concat NoneType to bytes
```

**Comment by muanis** [comment]
More Detailed

```
pi@pi-timelapse-2:~/raspberry-pi-projects/sixfab $ sudo python3 check_internet.py 
no internet, connect
> /home/pi/raspberry-pi-projects/sixfab/pppd.py(84)__init__()
-> outp = self.proc.stdout.read()
(Pdb) c
> /home/pi/raspberry-pi-projects/sixfab/pppd.py(83)__init__()
-> import pdb; pdb.set_trace()

(Pdb) outp
'pppd options in effect:\ndebug\t\t# ... long text ... (from /etc/ppp/options)\nDevice ttyUSB3 is locked by pid 3962\n'
(Pdb) self.proc.stdout
<_io.TextIOWrapper name=4 encoding='UTF-8'>
(Pdb) self.proc.stdout.read()
*** TypeError: can't concat NoneType to bytes
(Pdb) 

```

**Comment by COUR4G3** [comment]
You can try with `.readline` instead of `.read`. Still trying to setup an environment with PPP.

**Comment by COUR4G3** [comment]
Okay, found the issue, it's `universal_newlines` clashing with the non-blocking part. I'm pushing a fix that removes `universal_newlines` and then just interact with the binary instead.

**Comment by COUR4G3** [comment]
And pushed 1.0.4 to GitHub and PyPi
